# Generated by Django 5.0.6 on 2024-06-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('EXC', 'Executor'), ('CUS', 'Customer')], default=None, max_length=3, null=True),
        ),
    ]
