# Generated by Django 5.0.6 on 2024-06-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('WAE', 'Waiting executor'), ('INP', 'In process'), ('REL', 'Realized')], default='WAE', max_length=3),
        ),
    ]
